version: 2
  
general:
# Uncomment the following to specify only a specific branch
#   branches:
#     only:
#       - dev # specific branch
#       - /dev-.*/ # or regexes

jobs:
  build:
    machine: true
    working_directory: ~/ci_app
    
    steps:
      - checkout

      - run:
          name: Install Salesforce CLI (sfdx) via npm
          command: |
            # Install Salesforce CLI (sfdx) globally via npm
            npm install -g @salesforce/cli
            # Verify sfdx installation
            sf --version
      - run:
          name: Create hub key
          command: |
            echo 'make hub key'
            #- mkdir keys
            #- echo $HUB_SERVER_KEY_HEX | xxd -r -ps >> keys/hub.key
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
            #- openssl rsa -in keys/hub.key -check -noout
          ### Uncomment the following if performing deployments
          #- echo 'make deploy key'
          #- echo $DEPLOY_SERVER_KEY_HEX | xxd -r -ps >> keys/deploy.key
          #- openssl rsa -in keys/deploy.key -check -noout
          #- sfdx force:auth:jwt:grant --clientid $DEPLOY_CONSUMER_KEY --jwtkeyfile keys/deploy.key --username $DEPLOY_SFDC_USER -a deploy
      - run:
          name: Authorize and Create Scratch Org
          command: |
            echo 'Running tests'
            sf org login jwt  --client-id $HUB_CONSUMER_KEY --jwt-key-file  assets/server.key --username $HUB_SFDX_USER --set-default-dev-hub --alias devhub
            sf org create scratch --definition-file ~/ci_app/config/project-scratch-def.json --alias circle_build_$CIRCLE_BUILD_NUM --wait 2
            sf project deploy start --target-org circle_build_$CIRCLE_BUILD_NUM
      - run:
          name: Run Apex Tests
          command: |
            mkdir -p ~/junit
            sf apex run test --target-org circle_build_$CIRCLE_BUILD_NUM --no-store --output-dir ~/junit --result-format junit --wait 5
      - store_test_results:
          path: ~/junit
      - run:
          name: Deploy to Scratch Org
          command: |
            echo 'Deployment in Progress'
            sf project deploy start --target-org circle_build_$CIRCLE_BUILD_NUM
      - run:
          name: Delete Useless Scratch Org
          command: |
            sf org delete scratch --target-org circle_build_$CIRCLE_BUILD_NUM --no-prompt

### Uncomment the following if performing deployments
#deployment:
#  override:
#    - sfdx force:source:convert -r force-app -d testDeploy
#    - . cleanupDeploy.sh
#    - sfdx force:mdapi:deploy -d testDeploy/ -u deploy -w 2
